<div class="option-wrapper">
    <div class="option">
        <input type="radio" id="insert" name="option" value="insert" required>
        <label for="insert">Insert</label>
    </div>
    <div class="option">
        <input type="radio" id="update" name="option" value="update">
        <label for="update">Update</label>
    </div>
    <div class="option">
        <input type="radio" id="delete" name="option" value="delete">
        <label for="delete">Delete</label>
    </div>
</div>